domain_path: C:\Users\danim\OneDrive\Escritorio\Pra4_Vitis\platform\export\platform\sw\standalone_microblaze_0
app_src_dir: D:\Vitis\Vitis\2023.2\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
